# Generated by Django 3.2 on 2023-11-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giftCards', '0012_giftcardv2_redeemv2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('redemption_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0.0)),
                ('receipent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='generated', max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dapp_image', to='giftCards.giftcardimage')),
            ],
        ),
    ]
